[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "aws.sns"
version = "@toml.version@"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Communication/Push Notifications", "Cost/Paid", "Vendor/Amazon", "Area/Communication", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.sns"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
